### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by haofusheng** [tmensink/deepncm#1]
Hi, I'm following your work! 

When I run the 'deepncm_do.sh', I come across the following TypeError

TypeError: Failed to convert object of type <class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'> to Tensor. Contents: <PrefetchDataset shapes: ((?, 32, 32, 3), (?, 100)), types: (tf.float32, tf.float32)>. Consider casting elements to a supported type.

Can you help me fix it?

Thanks!

**Comment by tmensink** [comment]
Hi, thanks for your interest in DeepNCMs.

Unfortunately, I'm not able to reproduce this error myself, please try (ensure) the following:

1. Verify Tensorflow is at version 1.6.0 (that is the version it is tested with, will clarify that)
2. Initialise the submodule (`git submodule update --init`)
3. Download and install CIFAR10 in the following directory: `/tmp/deepncm/cifar10_data`
4. Run a single experiment, eg `python cifar10_deepncm.py --dataset cifar10 --ncmmethod softmax -l 0.05`

If this works, I will update README and documentation accordingly. I probably hard coded the data directory somewhere. Best Thomas

**Comment by haofusheng** [comment]
Thank you for your kind suggestions!

My software Environment: python 2.7, and Tensorflow 1.4.0. 

When  I upgraded Tensorflow from 1.4.0 to 1.6.0, this issue was solved.

With the following modification: resnet_ncm.py:113 ncm['method'].casefold() is replaced with ncm['method'].lower(), I run the code successfully.

Thanks!

**Comment by tmensink** [comment]
Will add that to the readme. Thanks
